### ISSUE TITLE
[bug] - 夜莺如果部署在超算服务器的 K8S 上，应用资源太多，redis 将会导致内存占用完，导致服务器无法登录使用；

### ISSUE THREAD

**Issue by ai-liuys** [flashcatcloud/n9e-helm#121]
操作系统: Centos 7.8
内核版本: 5.4+
K8S版本：v1.20+
问题现象： K8S 系统单节点运行了 200+ 的应用服务，运行 pod 超过 300 个，直接使用夜莺进行服务部署，由于初始状态需要采集超多的监控指标，redis 资源规格未作限制。会在短时间内消耗完全的系统内存，导致系统无法登录，之恩那个重启后删除夜莺组件才可以恢复。

解决办法：调整夜莺的初始配置，避免夜莺的组件超过系统资源规格。

**Comment by kongfei605** [comment]
多个组件都没有设置资源限制，可以根据自己的资源情况自行设置。我没办法判断你的集群规模和资源情况。
