### ISSUE TITLE
prometheus 镜像需要固定版本至老的v2.51.2左右

### ISSUE THREAD

**Issue by sunFlying** [flashcatcloud/n9e-helm#123]
prometheus 官方镜像lasted更新到了3.0版本，打开writer操作不再适用。
![image](https://github.com/user-attachments/assets/9d23c31d-2903-4290-affb-e20015eb9764)

试了下回滚prometheus 到旧版，可以了
建议重新适配，或者固定下镜像tag

**Comment by sunFlying** [comment]
![image](https://github.com/user-attachments/assets/f0391c1f-8ee0-4326-935d-8b2648ce8222)

**Comment by sunFlying** [comment]
![image](https://github.com/user-attachments/assets/c122a56b-f278-4bb4-a77b-a68e3cea95d8)

**Comment by kongfei605** [comment]
感谢反馈，我们来修改下

**Comment by kongfei605** [comment]
https://github.com/flashcatcloud/n9e-helm/pull/124 已修改
