### ISSUE TITLE
telegraf 无权限连接docker sock

### ISSUE THREAD

**Issue by wkjun** [flashcatcloud/n9e-helm#29]
夜莺版本:
5.6.3

问题和复现方法:

```
helm install nightingale ./n9e-helm -n monitoring --create-namespace
```
```
dial unix /var/run/docker.sock: connect: permission denied
```
按官方issues讨论,获取k8s主机的docker group id,并通过k8s设置为`telegraf`的运行用户组即可.

本集群docker group id 为 990

```
stat -c '%g' /var/run/docker.sock
990
```

1. 官方镜像的[dockerfile](https://github.com/influxdata/influxdata-docker/blob/2f72e6bfaf6d4d3ae7ded838214daf119d82f953/telegraf/1.22/alpine/Dockerfile)中未设置USER,默认是`root`运用启动容器,再以`telegraf`用户运行程序,故通过设置`securityContext.runAsGroup`无效.

2. bitinami镜像的[dockerfile](https://github.com/bitnami/bitnami-docker-telegraf/blob/1.22.4-debian-11-r0/1/debian-11/Dockerfile)中有设置USER,以`1001`用户启动容器,并以`1001`用户运行程序,故可通过设置`securityContext.runAsGroup`

一种参考处理方式:
替换镜像为: bitnami/telegraf:1.22.4
设置:         spec.template.spec.containers[0].command: ["telegraf"]
                 .spec.template.spec.containers[0].securityContext.runAsGroup: 990

参考:
https://github.com/influxdata/telegraf/issues/10050

**Comment by kongfei605** [comment]
感谢反馈。这个问题是因为telegraf 使用普通用户启动pod导致。参见dockerfile
<img width="1479" alt="4C5C9F88-8A05-484F-979B-181CF2ED02BB" src="https://user-images.githubusercontent.com/12164762/172348419-8ed1aeb5-6f22-4d77-a07c-e5e2c69fca33.png">
可以看telegraf的dockerfile 
https://github.com/influxdata/influxdata-docker/blob/master/telegraf/1.22/alpine/Dockerfile
telegraf是出于安全考虑，推荐的方案是给telegraf user添加访问docker权限（node上操作） 。 这个方案适用于 telegraf的uid 一致的情况。

如果会docker build image ，可以把图片红框的部分去掉，制作一个image 。 也有已经制作好的镜像，flashcatcloud/public:telegraf-1.22。 在values.yaml 中替换即可 https://github.com/flashcatcloud/n9e-helm/blob/master/values.yaml#L194

**Comment by kongfei605** [comment]
总结一下解决方案
1 去掉dockerfile中的adduser 部分或者使用 [flashcatcloud/public:telegraf-1.22](https://hub.docker.com/r/flashcatcloud/public) 替换
2 修改dockerfile中 ，指定uid； k8s 中指定run as group 
3 使用telegraf原有image，node节点上给telegraf 加入权限
