### ISSUE TITLE
host-telegraf-linux模版监控大盘fd无数据

### ISSUE THREAD

**Issue by wkjun** [flashcatcloud/n9e-helm#30]
情况:
![image](https://user-images.githubusercontent.com/8346977/173170525-939dbfcf-a4c1-47bb-8f87-ef3af90148cb.png)
解决办法:
telegraf-config configmap 中添加参数: `[[inputs.linux_sysctl_fs]]`

参考: https://w2.influxdata.com/integration/linux-sysctl-fs/

**Comment by kongfei605** [comment]
感谢反馈，有些选项没有开。 可以修改template的telegraf configmap ，欢迎提PR

**Comment by kongfei605** [comment]
新的采集器categraf 已经默认包含这些基础采集指标（cpu disk diskio docker kernel kernel_vmstat linux_sysctl_fs mem net netstat processes system）， 可以更新到v5.8.0-1
