### ISSUE TITLE
script-cm.yaml里使用的python脚本不存在

### ISSUE THREAD

**Issue by kevinslong** [flashcatcloud/n9e-helm#40]
{{- if eq .Values.nserver.type "internal" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nserver-script
data:
  {{ (.Files.Glob "scripts/*.py").AsConfig | indent 2 }}
{{- end -}}

**Comment by kongfei605** [comment]
有些python的语法会和helm冲突， 后续有时间再处理。 需要用notify.py  可以手动挂载kubectl create cm nserver-script -n xxx --from-file=./notify.py（或notify.py 所在的目录）

这个issue先close了
