### ISSUE TITLE
统一 docker image repository

### ISSUE THREAD

**Issue by laiwei** [flashcatcloud/n9e-helm#43]
我们可以考虑把  nightingale 的image 仓库，统一放到 flashcatcloud/下面。

``` image:
      repository: docker.io/ulric2019/nightingale
      tag: 5.9.4
```

**Comment by kongfei605** [comment]
重新修改了values.yaml ,已经统一了

**Comment by kongfei605** [comment]
n9e的github action已经修改了，images会自动推到flashcatcloud 下（5.9.5已经自动推送了）。 

这个issue关闭了
