### ISSUE TITLE
nserver服务启动失败，找不到recording_rule这张表

### ISSUE THREAD

**Issue by noovertime7** [flashcatcloud/n9e-helm#47]
nserver服务启动失败，找不到recording_rule这张表
![image](https://user-images.githubusercontent.com/100392073/178180362-85b0f2af-351e-49fa-a697-598af50ef4d3.png)

2022/07/11 10:53:55 /home/runner/work/nightingale/nightingale/src/models/recording_rule.go:197 Error 1146: Table 'n9e_v5.recording_rule' doesn't exist
[0.253ms] [rows:0] SELECT count(*) as total,max(update_at) as last_updated FROM `recording_rule` WHERE cluster = 'Default'
failed to sync recording rules: failed to exec RecordingRuleStatistics: Error 1146: Table 'n9e_v5.recording_rule' doesn't exist

**Comment by noovertime7** [comment]
页面可以正常登录，nserver服务无法启动

**Comment by UlricQin** [comment]
各个版本升级的时候记得执行sql https://github.com/ccfos/nightingale/releases，sql的执行不能跳着版本执行

**Comment by noovertime7** [comment]
刷入sql后，已成功运行，谢谢
