### ISSUE TITLE
helm 部署异常

### ISSUE THREAD

**Issue by Robby3345** [flashcatcloud/n9e-helm#64]
[root@m1 helm]# helm install nightingale ./n9e-helm -n n9e --create-namespace
Error: INSTALLATION FAILED: template: nightingale/templates/_helpers.tpl:244:9: executing "nightingale.redis.mode" at <eq .Values.redis.type "internal">: error calling eq: incompatible types for comparison

请问这个是什么异常？目前只修改了values.yaml 中expose方式和存储，其他未改动

**Comment by kongfei605** [comment]
参考 https://github.com/flashcatcloud/n9e-helm/pull/65

templates/_helpers.tpl 244-248行替换为
`
  {{- with .Values.redis }}
    {{- ternary "standalone" .external.mode (eq .type "internal") }}
  {{- end }}
`

**Comment by Robby3345** [comment]
thanks
