### ISSUE TITLE
k8s运行时为containerd时运行异常

### ISSUE THREAD

**Issue by tianxin8206** [flashcatcloud/n9e-helm#66]
categraf挂载了docker.sock，如果运行时为containerd程序无法正常运行

**Comment by LinkMaq** [comment]
> categraf挂载了docker.sock，如果运行时为containerd程序无法正常运行

参考这个 https://github.com/flashcatcloud/n9e-helm/pull/62

**Comment by kongfei605** [comment]
可以参考@LinkMaq提供的信息，不挂载docker.sock
