### ISSUE TITLE
categraf启动失败

### ISSUE THREAD

**Issue by xuzheng0017** [flashcatcloud/n9e-helm#70]
categraf日志报错：
2022/09/16 08:02:13 main.go:121: I! runner.vm_limits: (soft=unlimited, hard=unlimited)

2022/09/16 08:02:13 main.go:120: I! runner.fd_limits: (soft=1048576, hard=1048576)

2022/09/16 08:02:13 main.go:119: I! runner.hostname: cce-0002

2022/09/16 08:02:13 main.go:118: I! runner.binarydir: /usr/bin

Failed to set additional capabilities on /usr/bin/categraf

/entrypoint.sh: 5: setcap: not found

2022/09/16 08:02:09 main.go:65: F! failed to init config: failed to load configs of dir: /etc/categraf/conf err:toml: line 45 (last key "writers"): expected a top-level item to end with a newline, comment, or EOF, but got '[' instead

用tomlv检查了文件，格式是正确的。不知道什么原因。。。

**Comment by UlricQin** [comment]
/etc/categraf/conf/config.toml 最后加个空行试试

**Comment by xuzheng0017** [comment]
> /etc/categraf/conf/config.toml 最后加个空行试试

可以了，感谢哦~
