### ISSUE TITLE
k8s高版本报错

### ISSUE THREAD

**Issue by linorwang** [flashcatcloud/n9e-helm#79]
k8s版本v1.25.3部署夜莺，其中nightingale-categraf报错，提示无法挂载本地docker目录，容器运行时为container，事件提示报错，报错信息如下，应该是默认容器运行时为docker，请兼容container
![image](https://user-images.githubusercontent.com/23013733/216208922-519f3a1c-c47d-499d-b6fe-2b292a630c33.png)
![image](https://user-images.githubusercontent.com/23013733/216210108-7e86527a-66e7-473f-85c5-9a9696c3459b.png)

**Comment by kongfei605** [comment]
https://github.com/flashcatcloud/n9e-helm/issues/66
