### ISSUE TITLE
Error 1064: You have an error in your SQL syntax;

### ISSUE THREAD

**Issue by liangjaden** [flashcatcloud/n9e-helm#81]
2023/03/20 16:52:06 [31;1m/home/runner/work/nightingale/nightingale/src/models/target.go:82 [35;1mError 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'cluster = ?' at line 1
[0m[33m[0.998ms] [34;1m[rows:0][0m SELECT count(*) as total,max(update_at) as last_updated FROM `target` WHERE cluster = 'Default'
failed to sync targets: failed to exec TargetStatistics: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'cluster = ?' at line 1

Mysql version: 5.7

**Comment by kongfei605** [comment]
你部署的n9e是哪个版本？

**Comment by liangjaden** [comment]
V15.5.0的

**Comment by liangjaden** [comment]
![image](https://user-images.githubusercontent.com/54787532/226564237-c784de4e-c1f7-4a6c-a59e-6f5981aa6f1e.png)
确认了是腾讯云TDSQL-C MYSQL的问题，如图所示。
另想确认下，参考客服的解决方案，我虽然修改哪些代码？谢谢
@kongfei605

**Comment by kongfei605** [comment]
今天先加一个n9e V6版本，欢迎试用

**Comment by liangjaden** [comment]
好的感谢~

**Comment by kongfei605** [comment]
> 好的感谢~

抱歉，上周有点忙。今天刚发布v6.0.0-ga.1版本。 这个是跟n9e的6.0.0-ga.1 对应的。

**Comment by liangjaden** [comment]
@kongfei605 感谢跟进~经测试V6也不兼容腾讯云的TDSQL-C MYSQL 5.7，报错一样。
2023/03/29 15:14:08 [31;1m/home/runner/work/nightingale/nightingale/models/alerting_engine.go:133 [35;1mError 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'cluster = ? and datasource_id=?' at line 1
[0m[33m[0.844ms] [34;1m[rows:0][0m SELECT count(*) FROM `alerting_engines` WHERE instance='nightingale-center-5465c4c9c6-xr8s6:17000' and cluster = 'default' and datasource_id=100000
2023-03-29 15:14:08.842608 WARNING naming/heartbeat.go:120 heartbeat with cluster  err:Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'cluster = ? and datasource_id=?' at line 1

我先在本地起一个mysql用了，感谢~~

**Comment by kongfei605** [comment]
这个是因为n9e代码中现在还没修改字段名称，n9e-helm用的是n9e的镜像，后续会做一下兼容避免这个问题。

**Comment by liangjaden** [comment]
明白~感谢跟进~期待越来越的n9e~
